modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="malcglffe"
version="1.0.0"
displayName="MaLCGLFFE"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ancep, MCreator"

[[dependencies.malcglffe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



